mode.production: false
app.name: 'event-pump'

server:
  host: "0.0.0.0"
  port: 8088
  gracefulShutdownTimeSec: 5
  perf.enabled: false

consul:
  enabled: true
  consulAddress: localhost:8500

redis:
  enabled: true
  address: localhost
  port: 6379
  database: 0

rabbitmq:
  enabled: true
  host: localhost
  port: 5672
  username: guest
  password: guest
  vhost: "/"

tracing.propagation.keys:
  - id
  - userno
  - username
  - role
  - roleno

goauth.client.enabled: false

sync:
  server-id: 100
  host: localhost
  port: 3306
  user: root
  password:

filter:
  include: ''
  exclude: ''

pipeline:
  - schema: 'fileserver'
    table: 'file_info'
    type: '^(INS)$'
    stream: 'vfm.file.saved'
    enabled: true

  - schema: 'fileserver'
    table: 'file_info'
    type: '^(UPD)$'
    stream: 'vfm.file.thumbnail.updated'
    enabled: true
    condition:
      column-changed:
        - "thumbnail"

  - schema: 'fileserver'
    table: 'file_info'
    type: '^(UPD)$'
    stream: 'vfm.file.name.updated'
    enabled: true
    condition:
      column-changed:
        - "name"