mode.production: true

app.name: "event-pump"

redis:
  enabled: true
  address: "redis"
  port: 6379
  username:
  password:
  database: 0

server:
  host: "0.0.0.0"
  port: 8088
  gracefulShutdownTimeSec: 5
  perf.enabled: false

consul:
  enabled: true
  consulAddress: consul:8500
  healthCheckUrl: /health

rabbitmq:
  enabled: true
  host: "rabbitmq"
  port: 5672
  username: "${rabbitmqusername}"
  password: "${rabbitmqpassword}"
  vhost: "/"

tracing.propagation.keys:
  - id
  - userno
  - username
  - role
  - roleno

logging.rolling.file: "/usr/src/logs/${app.name}.log"

goauth.report.enabled: true

sync:
  server-id: 100
  user: "${mysqlusername}"
  password: "${mysqlpassword}"
  host: "${mysqladdr}"
  port: 3306

filter:
  include: 'fileserver'
  exclude: ''

pipeline:
  - schema: 'fileserver'
    table: 'file_info'
    type: '^(INS)$'
    stream: 'event.bus.vfm.file.saved'
    enabled: true

  - schema: 'fileserver'
    table: 'file_info'
    type: '^(UPD)$'
    stream: 'event.bus.vfm.file.thumbnail.updated'
    enabled: true
    condition:
      column-changed:
        - "thumbnail"

  - schema: 'fileserver'
    table: 'file_info'
    type: '^(UPD)$'
    stream: 'event.bus.vfm.file.logic.deleted'
    enabled: true
    condition:
      column-changed:
        - "is_logic_deleted"