// auto generated by misoapi v0.2.16 at 2025/09/16 23:33:02 (CST), please do not modify
package pump

import (
	"github.com/curtisnewbie/miso/miso"
)

func init() {
	miso.HttpPost("/api/v1/create-pipeline", miso.AutoHandler(
		func(inb *miso.Inbound, req ApiPipeline) (any, error) {
			return nil, ApiCreatePipeline(inb.Rail(), req)
		})).
		Extra(miso.ExtraName, "ApiCreatePipeline").
		Desc(`Create new pipeline. Duplicate pipeline is ignored, HA is not supported.`)

	miso.HttpPost("/api/v1/remove-pipeline", miso.AutoHandler(
		func(inb *miso.Inbound, req ApiPipeline) (any, error) {
			return nil, ApiRemovePipeline(inb.Rail(), req)
		})).
		Extra(miso.ExtraName, "ApiRemovePipeline").
		Desc(`Remove existing pipeline. HA is not supported.`)

	miso.HttpGet("/api/v1/list-pipeline", miso.ResHandler(
		func(inb *miso.Inbound) ([]ApiPipeline, error) {
			return ApiListPipelines(inb.Rail())
		})).
		Extra(miso.ExtraName, "ApiListPipelines").
		Desc(`List existing pipeline. HA is not supported.`)

}
