// auto generated by misoapi v0.1.14-beta.3 at 2025/02/06 00:44:32, please do not modify
package pump

import (
	"github.com/curtisnewbie/miso/miso"
)

func init() {
	miso.IPost("/api/v1/create-pipeline",
		func(inb *miso.Inbound, req ApiPipeline) (any, error) {
			return nil, ApiCreatePipeline(inb.Rail(), req)
		}).
		Extra(miso.ExtraName, "ApiCreatePipeline").
		Desc("Create new pipeline. Duplicate pipeline is ignored, HA is not supported.")

	miso.IPost("/api/v1/remove-pipeline",
		func(inb *miso.Inbound, req ApiPipeline) (any, error) {
			return nil, ApiRemovePipeline(inb.Rail(), req)
		}).
		Extra(miso.ExtraName, "ApiRemovePipeline").
		Desc("Remove existing pipeline. HA is not supported.")

	miso.Get("/api/v1/list-pipeline",
		func(inb *miso.Inbound) ([]ApiPipeline, error) {
			return ApiListPipelines(inb.Rail())
		}).
		Extra(miso.ExtraName, "ApiListPipelines").
		Desc("List existing pipeline. HA is not supported.")

}
